INSERT INTO TB_MNGR_SETT (
    CD, CNN_FAILR_THRS_VAL, CNN_WARN_THRS_VAL, CNN_FAILR_ICON_ID, CNN_FAILR_WRD_COLR,
    CNN_WARN_ICON_ID, CNN_WARN_WRD_COLR, CNN_SUCS_ICON_ID, CNN_SUCS_WRD_COLR,
    DLY_SUCS_RT_THRS_VAL, DD7_SUCS_RT_THRS_VAL, MTHL_SUCS_RT_THRS_VAL, MC6_SUCS_RT_THRS_VAL, YY1_SUCS_RT_THRS_VAL,
    SUCS_RT_SUCS_ICON_ID, SUCS_RT_SUCS_WRD_COLR, SUCS_RT_WARN_ICON_ID, SUCS_RT_WARN_WRD_COLR,
    CHRT_COLR, CHRT_DSP_YN, GRASS_CHRT_MIN_COLR, GRASS_CHRT_MAX_COLR
) VALUES (
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s,
    %s, %s, %s, %s
)
