SELECT
    TO_CHAR(MIN(EVNT_OCCR_TIME AT TIME ZONE 'Asia/Seoul'), 'YYYY-MM-DD') AS min_date,
    TO_CHAR(MAX(EVNT_OCCR_TIME AT TIME ZONE 'Asia/Seoul'), 'YYYY-MM-DD') AS max_date
FROM TB_CON_HIST_EVNT_LOG
